name: "action-semantic-release"
description: "Automatically release a new version on GitHub"
inputs:
  github-token:
    description: "This is just an example input for now"
    required: true
    default: "default"
  dry-run:
    description: "Whether to do a release dry-run"
    required: false
    default: false
outputs:
  last-version:
    description: "The last released version"
  next-version:
    description: "The next released version"
  version-released:
    description: "Whether a version was released. Note that this would be true even with dry-run=true"
runs:
  using: 'docker'
  image: ./
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.dry-run }}
