name: "action-semantic-release"
description: "Automatically release a new version on GitHub"
inputs:
  github-token:
    description: "This is just an example input for now"
    required: true
    default: "default"
outputs:
  version:
    description: "The most recently released version"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
