name: "action-semantic-release"
description: "Automatically release a new version on GitHub"
inputs:
  github-token:
    description: "This is just an example input for now"
    required: true
    default: "default"
  dry-run:
    description: "Whether to do a release dry-run"
    required: false
    default: false
outputs:
  version:
    description: "The most recently released version"
runs:
  using: 'docker'
  image: 'docker://outoforbitdev/action-semantic-release:v1.2.0'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.dry-run }}
