#!/usr/bin/env sh

LAST_VERSION=$1
NEXT_VERSION=$2
VERSION_RELEASED=$3

echo $LAST_VERSION
echo "last-version=$LAST_VERSION" >> $GITHUB_OUTPUT
echo $NEXT_VERSION
echo "last-version=$NEXT_VERSION" >> $GITHUB_OUTPUT
echo $VERSION_RELEASED
echo "last-version=$VERSION_RELEASED" >> $GITHUB_OUTPUT
