name: Dry Run
permissions: read-all
on:
  push
jobs:
    semantic-release:
      runs-on: ubuntu-latest
      name: Dry Run Release
      outputs:
        versionReleased: ${{steps.semanticrelease.outputs.version-released}}
        version: ${{steps.semanticrelease.outputs.next-version}}
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            persist-credentials: false
        - name: Semantic Release
          uses: ./
          id: semanticrelease
          with:
            github-token: ${{ secrets.RELEASE_TOKEN }}
            skip-changelog: ${{ github.ref_name != 'main' }}
            dry-run: true
            debug: true
        - name: Version Summaries
          env:
            LAST_VERSION: ${{ steps.semanticrelease.outputs.last-version }}
            NEXT_VERSION: ${{ steps.semanticrelease.outputs.next-version }}
            VERSION_RELEASED: ${{ steps.semanticrelease.outputs.versionReleased}}
          run: echo "### Version Summaries" >> $GITHUB_STEP_SUMMARY; echo "* Last version - $LAST_VERSION" >> $GITHUB_STEP_SUMMARY; echo "* Next version - $NEXT_VERSION" >> $GITHUB_STEP_SUMMARY