name: Release
run-name: Releasing
on:
  push:
    branches: [main]
jobs:
  Release:
    runs-on: ubuntu-latest
    name: Semantic Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: ./
        id: semanticrelease
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Latest version
        run: echo "Latest version ${{ steps.semanticrelease.outputs.version}}"
