name: Release
run-name: ${{ github.actor }} is creating a release
on:
  push:
    branches: [main]
jobs:
  Release:
    runs-on: ubuntu-latest
    name: Semantic Release
    steps:
      - name: Semantic Release
        uses: outoforbitdev/action-semantic-release@v1.0.0
        id: semanticrelease
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the output time
        run: echo "The time was ${{ steps.semanticrelease.outputs.time}}"
