name: Release
permissions: read-all
on:
  push:
    branches:
      - main
      - beta
      - dev
      - staging
jobs:
  test-docker-image:
    runs-on: ubuntu-latest
    name: Test Action
    outputs:
      success: ${{steps.docker-test.outputs.success}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Docker Image
        uses: outoforbitdev/action-docker-test@v1.0.0-staging.1
        id: docker-test
        with:
          test-command: "sh ./test.sh"
  release-action:
    runs-on: ubuntu-latest
    name: Check Release Version
    needs: test-docker-image
    if: ${{ needs.test-docker-image.outputs.success }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Semantic Release
        uses: ./
        id: semantic-release
        with:
          github-token: ${{ secrets.RELEASE_TOKEN }}
          skip-changelog: ${{ github.ref_name != 'main' }}
          debug: true
      - name: Version Summaries
        env:
          LAST_VERSION: ${{ steps.semantic-release.outputs.last-version }}
          NEXT_VERSION: ${{ steps.semantic-release.outputs.next-version }}
          VERSION_RELEASED: ${{ steps.semantic-release.outputs.version-released}}
        run: echo "### Version Summaries" >> $GITHUB_STEP_SUMMARY; echo "* Last version - $LAST_VERSION" >> $GITHUB_STEP_SUMMARY; echo "* Next version - $NEXT_VERSION" >> $GITHUB_STEP_SUMMARY
