name: Test
run-name: Running Tests
on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - beta
      - dev
      - staging
permissions:
  contents: write
jobs:
  Test:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Release
        uses: ./
        id: semanticrelease
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
      - name: Version Summaries
        env:
          LAST_VERSION: ${{ steps.semanticrelease.outputs.last-version }}
          NEXT_VERSION: ${{ steps.semanticrelease.outputs.next-version }}
          VERSION_RELEASED: ${{ steps.semanticrelease.outputs.versionReleased}}
        run: echo "### Version Summaries" >> $$GITHUB_STEP_SUMMARY; echo "* Last version - $LAST_VERSION" >> $$GITHUB_STEP_SUMMARY; echo "* Next version - $NEXT_VERSION" >> $$GITHUB_STEP_SUMMARY
