name: Test
run-name: Running Tests
on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - beta
      - dev
      - staging
permissions:
  contents: read
jobs:
  Test:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test Build
        run: docker build .
      - name: Test Release
        uses: ./
        id: semanticrelease
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Output version
        run: echo "Latest version is ${{ steps.semanticrelease.outputs.next-version}}"
