name: Test Action
permissions: read-all
on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - beta
      - alpha
      - staging
jobs:
  test-docker-image:
    runs-on: ubuntu-latest
    name: Test Action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Docker Image
        uses: outoforbitdev/action-docker-test@v1.0.0-staging.1
        id: dockertest
        with:
          test-command: "sh ./test.sh"
      - name: Test Action (No Changelog)
        uses: ./
        id: actiontestnochange
        with: 
          github-token: ${{ secrets.RELEASE_TOKEN }}
          dry-run: true
          skip-changelog: true
          debug: true
      - name: Test Action (With Changelog)
        uses: ./
        id: actiontest
        with: 
          github-token: ${{ secrets.RELEASE_TOKEN }}
          dry-run: true
          debug: true
