name: Test Docker Image
permissions: read-all
on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - beta
      - dev
      - staging
jobs:
  test-docker-image:
    runs-on: ubuntu-latest
    name: Test Docker Image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Docker Image
        uses: outoforbitdev/action-docker-test@v1.0.0-staging.1
        id: dockertest
        with:
          test-command: "sh ./test.sh"
      - name: Output
        run: echo ${{steps.dockertest.outputs.success}}
