name: Test
run-name: Running Tests
on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - beta
      - dev
      - staging
permissions:
  contents: write
jobs:
  Test:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Docker Image
        uses: outoforbitdev/action-docker-test@v1.0.0-staging.1
        id: dockertest
        with:
          test-command: "sh ./test.sh"
      - name: Output
        run: echo ${{steps.dockertest.outputs.success}}
